drone:
  default: &default_drone
    dimensions:
      length: 0.5
      width: 0.5
      height: 0.2
    mass: 1.5  # kg
    max_velocity:
      linear: 10.0  # m/s
      angular: 2.0  # rad/s
    max_acceleration:
      linear: 5.0  # m/s^2
      angular: 1.0  # rad/s^2
    battery:
      capacity: 5000  # mAh
      voltage: 11.1  # V
      discharge_rate: 25  # C
       sensors:
      camera:
        resolution: [640, 480]
        fov: 90  # degrees
        update_rate: 30  # Hz
      imu:
        update_rate: 100  # Hz
        noise:
          gyroscope: 0.001  # rad/s
          accelerometer: 0.01  # m/s^2
      gps:
        update_rate: 10  # Hz
        position_accuracy: 2.5  # meters
    pollination:
      motor_speed: 1000  # RPM
      effective_range: 0.1  # meters

drone_1:
  <<: *default_drone
  name: "pollibee_1"
  initial_position: [0, 0, 1]  # [x, y, z] in meters

drone_2:
  <<: *default_drone
  name: "pollibee_2"
  initial_position: [1, 1, 1]  # [x, y, z] in meters
