greenhouse:
  dimensions:
    length: 20  # meters
    width: 10   # meters
    height: 5   # meters
  temperature: 25  # Celsius
  humidity: 60  # percent
  co2_level: 1000  # ppm

plants:
  - type: "tomato"
    growth_stages: ["seedling", "vegetative", "flowering", "fruiting"]
    pollination_period: [30, 60]  # days from start of flowering
    layout:
      rows: 5
      plants_per_row: 10
      row_spacing: 1.5  # meters
      plant_spacing: 0.5  # meters
  - type: "cucumber"
    growth_stages: ["seedling", "vegetative", "flowering", "fruiting"]
    pollination_period: [45, 90]  # days from start of flowering
    layout:
      rows: 3
      plants_per_row: 15
      row_spacing: 2.0  # meters
      plant_spacing: 0.3  # meters

weather:
  wind:
    mean_speed: 0.5  # m/s
    direction: [1, 0, 0]  # [x, y, z] vector
    turbulence: 0.1  # standard deviation
  light:
    intensity: 1000  # lux
    daily_cycle: true
    sunrise: "06:00"
    sunset: "18:00"
