#vf on 16/10
simulation:
  duration: 3600  # seconds
  time_step: 0.01  # seconds
  real_time_factor: 1.0

environment:
  type: greenhouse
  dimensions: &env_dim
    x: 50.0
    y: 30.0
    z: 10.0
  temperature: &temp_params
    mean: 25.0
    variance: 2.0
  humidity: &humidity_params
    mean: 60.0
    variance: 5.0

wind:
  enabled: true
  model: "dryden"
  parameters:
    mean_speed: 2.0
    turbulence_intensity: 0.1

drones:
  - &default_drone
    model: "pollibee_v1"
    sensors:
      - type: "camera"
        update_rate: 30
        resolution: [640, 480]
      - type: "imu"
        update_rate: 100
    battery:
      capacity: 5000  # mAh
      discharge_rate: 0.1  # C
  - <<: *default_drone
    name: "drone_1"
    initial_position: [0, 0, 1]
  - <<: *default_drone
    name: "drone_2"
    initial_position: [10, 10, 1]

plants:
  distribution:
    type: "random"
    density: 0.1  # plants per square meter
  growth_model:
    type: "logistic"
    parameters:
      growth_rate: 0.01
      carrying_capacity: 1.0

pollination:
  success_rate:
    distance_function:
      type: "exponential_decay"
      scale: 0.5
  pollen_depletion_rate: 0.1

logging:
  enabled: true
  frequency: 1  # Hz
  output_directory: "../data/simulation_results"
