# YOLO configuration file

# Model settings
model:
  architecture: yolov11
  weights: yolov11.weights
  config: yolov11.cfg

# Detection settings
detection:
  threshold: 0.5
  confidence: 0.5
  nms_threshold: 0.4

# Image settings
image:
  width: 416
  height: 416

# ROS settings
ros:
  topic: image_with_detections
  node_name: yolo_detector
